export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const IS_LOADING = 'IS_LOADING'
export const DONE_LOADING = 'DONE_LOADING'

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'